lib/kitchen/verifier/inspec.rb
I would like to catch failure from Inspec with `kitchen verify`.
=> raise ActionFailed when inspec returns other than 0.

lib/kitchen/verifier/inspec.rb, spec/kitchen/verifier/inspec_spec.rb
Test Kitchen's default verifier, Busser, has support for loading helper files which include things like:
* spec_helper
* InSpec custom resources
* RSpec shared examples
* RSpec shared contexts
* RSpec custom matchers
These helper files are meant to be shared amongst all test suites in a project structure like:
```
test/integration/
├── helpers
│   └── <VERIFIER>
│       ├── spec_helper.rb
│       └── support
│           └── some_file.rb
├── suite1
│   └── <VERIFIER>
│       └── some_spec.rb
└── suite2
   └── <VERIFIER>
       └── some_spec.rb
```
Some real world examples can be seen at:
https://github.com/chef-cookbooks/jenkins/tree/master/test/integration
https://github.com/chef-cookbooks/languages/tree/master/test/integration
https://github.com/chef-cookbooks/omnibus/tree/master/test/int …
=> support test suite helpers

.rubocop.yml, Gemfile, Guardfile, Rakefile, bin/console, bin/setup, kitchen-inspec.gemspec, lib/kitchen/verifier/inspec.rb, lib/kitchen/verifier/inspec_version.rb, spec/kitchen/verifier/inspec_spec.rb, spec/spec_helper.rb
...such that [this](https://github.com/chef/kitchen-inspec/blob/sr/fix19/lib/kitchen/verifier/inspec.rb#L57) doesn't fire. Fixes #19.
=> Fix tests and activate linting for CI

kitchen-inspec.gemspec
this is a public gem, so the default rubygems is fine.
=> remove gem push restriction

lib/kitchen/verifier/inspec.rb, spec/kitchen/verifier/inspec_spec.rb
This implements https://github.com/chef/kitchen-inspec/issues/26
=> Specify inspec output format from kitchen.yml

Gemfile, kitchen-inspec.gemspec
The dependency on test-kitchen is breaking chefdk. I think this will fix it.
cc @tyler-ball @chris-rock @fnichol
=> Make test-kitchen a dev dependency

lib/kitchen/verifier/inspec.rb
Also fixes the hilariously wrong exception.
Fixes #31
=> Allow transports which are subclasses of the core ones.

.gitignore, .travis.yml, Gemfile, Rakefile, lib/kitchen/verifier/inspec.rb, test/integration/.kitchen.yml, test/integration/Berksfile, test/integration/cookbooks/os_prepare/metadata.rb, test/integration/cookbooks/os_prepare/recipes/default.rb, test/integration/test/integration/default/_debug_spec.rb, test/integration/test/integration/default/os_spec.rb
This PR introduces a real-world run of `kitchen-inspec` in combination with `test-kitchen`.
=> Add integration test with test-kitchen

lib/kitchen/verifier/inspec.rb
kitchen-dokken works with two conatiners:
- `data_container` that hosts chef-client
- `runner_container` is the target container
We extracted the ID from the wrong container. This PR fixes that.
=> bugfix: use the right container in combination with kitchen-dokken

Gemfile
branch chris-rock/winrm-properties-fix was merged and deleted
into test-kitchen master.
=> Point test-kitchen to master in Gemfile

.kitchen.yml, lib/kitchen/verifier/inspec.rb, spec/kitchen/verifier/inspec_spec.rb
This adds supports for remote profiles in Kitchen-InSpec. Just add the `inspec_tests` section to `.kitchen.yml` and those profiles will be executed in addition to the tests located in `test/integration`
```
suites:
- name: profile
run_list:
- recipe[os_prepare]
inspec_tests:
- https://github.com/nathenharvey/tmp_compliance_profile
```
=> Add support for remote profiles

.kitchen.yml, lib/kitchen/verifier/inspec.rb, spec/kitchen/verifier/inspec_spec.rb
- remove monkey patch for test-kitchen
- verify that local test directory exists
The syntax to load remote profiles changed to:
```
suites:
- name: contains_inspec
run_list:
- recipe[os_prepare]
verifier:
inspec_tests:
- https://github.com/nathenharvey/tmp_compliance_profile
```
=> Improve handling for remote profiles

lib/kitchen/verifier/inspec.rb
Hi,
I'm using Kitchen for Ansible with Docker.
I have a ssh configuration and multiple keys. Without the key_only set to true, NetSSH is trying all my keys before using the Kitchen key.
I think it makes sense to limit the keys used to the one kitchen is using.
=> Use only the keys provided by Kitchen

lib/kitchen/verifier/inspec.rb
Address #66 
For this change we are adding the ability to pass through `profiles_path` from `.kitchen.yml` into the `Inspec::Runner`.
Example `verifier` for `.kitchen.yml`:
```yaml
---
verifier:
name: inspec
profiles_path: repo/path/to/profiles
```
=> Add support for profiles_path

.kitchen.yml, .travis.yml, Berksfile, Rakefile, kitchen-inspec.gemspec, lib/kitchen/verifier/inspec.rb
allows kitchen-inspec to work with inspec supermarket profiles and profiles stored in Chef Compliance
fixes #80
superseeds https://github.com/chef/inspec/pull/703
You can define the profiles as following:
```
suites:
- name: supermarket
run_list:
- recipe[ssh-hardening]
verifier:
inspec_tests:
- supermarket://hardening/ssh-hardening
- name: compliance
run_list:
- recipe[ssh-hardening]
verifier:
inspec_tests:
- compliance://base/ssh
```
=> Supermarket and Compliance support

README.md, lib/kitchen/verifier/inspec.rb, spec/kitchen/verifier/inspec_spec.rb
This implements `sudo_command` option for the verifier.
Related to this in train: https://github.com/chef/train/pull/107
=> support for sudo_command

.travis.yml, Gemfile, kitchen-inspec.gemspec
Ruby 1.9 and 2.0 are EOL and we shouldn't be supporting them anymore.
#98 needs to get merged first for this to make sense
=> Require Ruby 2.1+

lib/kitchen/verifier/inspec.rb
This message leads me to believe I have to fix something since it says `Use`. By changing that word to `Using` it makes it clearer that it is purely an informational message as opposed to something I need to fix.
=> Make the info message clearer

README.md, lib/kitchen/verifier/inspec.rb, spec/kitchen/verifier/inspec_spec.rb
When using kitchen vagrant, inspec is targeting 127.0.0.1 with the forwarded port provided by kitchen:
```
$ kitchen verify
-----> Starting Kitchen (v1.13.2)
-----> Verifying <mysuite-centos6>...
Use `/Users/apop/git/myapache-cookbook/test/integration/mysuite` for testing
Target:  ssh://root@127.0.0.1:2222
```
This prevents resources like `ssl` from getting a real host they can connect to. This PR adds two config options to be able to specify the host and port to be used by inspec instead on relying on the kitchen ones. Output:
```
$ be kitchen verify
-----> Starting Kitchen (v1.6.0)
-----> Verifying <mysuite-centos6>...
Use `/Users/apop/git/myapache-cookbook/test/integration/mysuite` for testing
Target:  ssh://root@192.168.33.40:22
SSL/TLS on
✔  192.168.33.40:443 with protocol == …
```
=> Add host and port config options

.kitchen.yml, .travis.yml, lib/kitchen/verifier/inspec.rb, spec/kitchen/verifier/inspec_spec.rb, test/integration/duplicates/dup.rb
fixes https://github.com/chef/kitchen-inspec/issues/109
trying to work on a test for this....
=> fix duplicate testing when unique suite name

.kitchen.yml, .travis.yml, README.md, kitchen-inspec.gemspec, lib/kitchen/verifier/inspec.rb, test/integration/attributes/controls/example.rb, test/integration/attributes/inspec.yml, test/integration/profile-attribute.yml
implements #108
This PR depends on #1258
=> add attributes support in kitchen-inspec

README.md, lib/kitchen/verifier/inspec.rb, spec/kitchen/verifier/inspec_spec.rb
Hi,
in order to workaround issue https://github.com/chef/kitchen-inspec/issues/121 we came up with this implementation: support template format for _verifier.output_ parameter. Right now only *platform* and *suite* are supported, but it easy to add more parameters if they are needed. 
Default output is not modified, as well as custom path option. The only behavior updated here is when you define the output as format string (%{}), so given _platform_ or _suite_ flags they will be replace (in that way, you can specify an output value in the general _verifier_ section, but multiple inspec files will be created based on the flags.
Added unit test and README block explaining this feature.
Thanks @AgarFu for your help!
=> Support multiple outputs based on platform/test suite variables (issue 121)

lib/kitchen/verifier/inspec.rb
Do not print an info message saying that we are loading tests from the
test_base_dir unless we actually are. This can be confusing for
first-time users who may not even have that directory (if they used
ChefDK to generate the .kitchen.yml). Rather, iterate through the
targets that we _are_ testing and log those.
Signed-off-by: Tom Duffield <tom@chef.io>
=> Tweak logging for clarity

README.md, lib/kitchen/verifier/inspec.rb, spec/kitchen/verifier/inspec_spec.rb
This is analogous to `inspec exec` and friends.
=> allow filtering controls

lib/kitchen/verifier/inspec.rb, spec/kitchen/verifier/inspec_spec.rb
kitchen-inspec currently sends `keys_only` set to `true` which prevents net-ssh from properly using credentials provided by a user's SSH Agent. Train already does the right thing by checking the Agent for available identities and sets `keys_only` as needed.
Therefore, this change eliminates this config parameter and lets Train do The Right Thing.
Related to chef/train#183
=> Don't send keys_only config to InSpec/Train

lib/kitchen/verifier/inspec.rb, spec/kitchen/verifier/inspec_spec.rb
If a cookbook has an InSpec profile at `test/integration/default` and adds the profile to `verifier.inspec_tests`, kitchen-inspec would collect the profile twice and add both entries to the runner. This would cause a profile to be run twice.
This change refactors `#resolve_config_inspec_tests` to:
* expand any paths to an absolute path
* replace path strings that exist on the filesystem with a hash for
consistency with what local_suite_files returns (so deduplication works)
* eliminate any unnecessary keys from each inspec_tests entry to ensure
items can be deduplicated properly
=> Eliminate duplicate profiles being added to runner

CHANGELOG.md, lib/kitchen/verifier/inspec_version.rb
Signed-off-by: Adam Leff <adam@leff.co>
=> Release 0.20.0

lib/kitchen/verifier/inspec.rb
This adds a way to inject support for new transports in to the verifier. Combined with Train's existing plugin registry system, this will allow me to manage transports without direct support in kitchen-inspec.
=> Allow extending which transports are supported by kitchen-inspec

lib/kitchen/verifier/inspec.rb
This fixes Issue #152, by analyzing the proper parts of the Kitchen Transport connection options and applying them to the runner options for winrm.
Fixes #152
=> correctly configure HTTPS WinRM

lib/kitchen/verifier/inspec.rb, lib/kitchen/verifier/inspec_version.rb, spec/kitchen/verifier/inspec_spec.rb
Fixes https://github.com/chef/kitchen-inspec/issues/154
This PR introduces the new backend_cache option. This flag will default to true if not defined in your kitchen.yml.
=> Add the InSpec backend_cache option

.travis.yml, lib/kitchen/verifier/inspec.rb
When fixing an unrelated issue, the configuration keys necessary to properly fetch a profile via git AND specify a branch/tag/reference was inadvertently broken. This change properly restores that functionality.
Fixes #157
=> git fetcher: support branch/tag/ref

.travis.yml
Bundler is now included in ruby and set as a default gem. As such we need to remove the force uninstall bundler command (as you cannot remove a default gem). Leaving in the install command will confirm its always there.
=> Fix travis-ci bundler issue

Gemfile, kitchen-inspec.gemspec
This updates the gems for kitchen inspec to support inspec 2.0
Fixes https://github.com/chef/kitchen-inspec/issues/165
=> Update kitchen inspec to support inspec 2.0.

lib/kitchen/verifier/inspec.rb
This adds 101 to the list of approved exit codes. This allows kitchen-inspec to exit cleanly if we have a 0 or 101.
Ex: (before and after)
Errors will continue to exit with errors:
Fixes https://github.com/chef/inspec/issues/2773
=> Add inspec exit code 101 to the approved list

lib/kitchen/verifier/inspec.rb
Signed-off-by: Tim Pringle <tim.pringle@poweshell.amsterdam>
The --format option is being being deprecated and will be removed in inspec 3.0.
This change allows the use of the --reporter parameter in a Kitchen config file.
Usage example:
```
verifier:
name: inspec
reporter:
- progress
- json:/tmp/json.txt
```
NB: Unlike 'format', 'reporter' is always parsed as a collection. As such it must be written appropriately in your .yml file when there is only one parameter as well.
```
verifier:
name: inspec
reporter:
- progress
```
=> Add the 'reporter' configuration option to kitchen-inspec

.travis.yml
Use the latest patch releases, add 2.5.1, and remove the dist setting of
trusty which is the default now
=> Update ruby version in travis

Gemfile
=> Remove workaround for Ruby < 2.0

lib/kitchen/verifier/inspec.rb, spec/kitchen/verifier/inspec_spec.rb
Allow setting for proxy_command that was added to train here: https://github.com/chef/train/pull/227
Example config:
```
verifier:
proxy_command: ssh user@1.2.3.4 -W %h:%p 
```
My main use case for this is we use a bastion host and therefor I need to be able to jump through the appropriate hoop to reach my instance which I can do with the above example.
=> Add proxy_command transport setting to inspec runner

README.md
Since #183 the reporter feature can and should be used to define the InSpec output.
```yaml
verifier:
name: inspec
reporter: junit:path/to/results/%{platform}_%{suite}_inspec.xml
```
=> Don't use deprecated format feature in README

README.md
We have some new features that landed, but didn't make it into the readme. If we don't document them they don't exist for end users. This adds them and also shuffles around the usage docs.
=> Reshuffle the readme and add proxy/supermarket examples

lib/kitchen/verifier/inspec.rb
this pull request add support for test-kitchen docker_cli transport (https://github.com/marcy-terui/kitchen-docker_cli)
Signed-off-by: chrisLeeTW protosschris.tech@gmail.com
=> add new transport support - docker_cli.

kitchen-inspec.gemspec
Avoid shipping berksfile, Gemfile, the gemspec, and others. This will slim down the size of ChefDK by 25k
=> Slim the files that ship with the Gem

kitchen-inspec.gemspec
This allows us to use this driver with the latest inspec. I also remove d the changelog from the gem which aligns with our other gems.
=> Allow InSpec 3.0

.gitignore, kitchen-inspec.gemspec
These will ship in DK 4 so we need to get a version of kitchen-inspec out that supports them
=> Update to allow Test Kitchen 2.0 and InSpec 4.0

lib/kitchen/verifier/inspec.rb
Adds support with TestKitchen for InSpec's recently released relative path feature.
https://github.com/inspec/inspec/pull/4217
Lets you do something like this:
```yaml
suites:
- name: default
run_list:
- recipe[test::default]
verifier:
inspec_tests:
- test/integration/default
- name: my_other_cookbook
git: git@git.mycompany.net:TEAM/chef-cookbooks/my_other_cookbook.git
tag: master
relative_path: test/integration/default
```
=> Add relative path support for the GIT fetcher

README.md, lib/kitchen/verifier/inspec.rb
Currently, kitchen-inspec does not support InSpec plugins, as it directly calls the Runner. This PR implements a setting to enable loading of plugins (like additional inputs). The setting defaults to `false` to not break compatibility.
No filed issue so far.
=> Add setting to load Inspec plugins for additional functionality

.github/lock.yml, kitchen-inspec.gemspec
Thanks for pointing this out @satyanash. This fixes https://github.com/inspec/kitchen-inspec/issues/253
=> Require InSpec 2.2.64+ to support plugin v2

README.md, lib/kitchen/verifier/inspec.rb
This allows deactivating the input caching in InSpec to avoid values from previous suites to persist into follow-up runs.
For a detailed explanation see [InSpec PR #5211](https://github.com/inspec/inspec/pull/5211).
See [InSpec PR #5211](https://github.com/inspec/inspec/pull/5211).
=> Add ability to disable input caching in InSpec

kitchen-inspec.gemspec, lib/kitchen/verifier/inspec.rb
Informs test-kitchen that the `inspec` verifier should not be run multithreaded.  This is because Chef InSpec is not thread-safe, due to RSpec not being thread safe; when run multithreaded, random test failures or test count inaccuracies can occur, as well as random `No method each for nil::NilClass` errors. See #167 and https://github.com/test-kitchen/test-kitchen/issues/1530 for details.
~PR set as draft until https://github.com/test-kitchen/test-kitchen/pull/1678 merges and the TK version is bumped, because this needs to have an updated version pin against test-kitchen in the kitchen-inspec gemspec.~ TK 2.7.0 includes the feature.
Closes #167
=> Declare kitchen-inspec to be run serially

README.md, lib/kitchen/verifier/inspec.rb
This change tells the Chef InSpec plugin system to scan for installed plugins before creating the InSpec Runner. This is important, because the Runner validates which Reports are valid based on the known plugins at the time. 
In addition, this change changes the default value for the `load_plugins` config option to be `true`.  Users are routinely bitten by this option, and as we move more functionality into plugins, the default should clearly be to load plugins by default, unless told not to for performance reasons, in which case we assume the user knows what they are doing.
Updated the README accordingly.
Fixes https://github.com/inspec/inspec/issues/5102
=> Load plugins earlier; load plugins by default

kitchen-inspec.gemspec
Signed-off-by: Pranay Singh <i5singh.pranay@gmail.com>
Enhancement to loosen the hashie gem dependencies to allow 4.x which resolves warnings on ruby 2.6 and 2.7 
- https://github.com/inspec/kitchen-inspec/issues/248
=> Loosening the hashie dep to allow 4.x

lib/kitchen/verifier/inspec.rb
Kitchen-inspec supplies an `opts` argument to InSpec which was removed pre-1.0.0 there. The InSpec source even states:
`@params _opts [Hash] Unused, but still here to avoid breaking kitchen-inspec`
see https://github.com/inspec/inspec/blob/master/lib/inspec/runner.rb#L193
Trivial code clean-up only
=> Fix call with deprecated options hash

README.md, lib/kitchen/verifier/inspec.rb
Signed-off-by: Pranay Singh <i5singh.pranay@gmail.com>
kitchen-inspec the default for backend_cache is disabled so running test cases (against a windows 2016 instance) without cache enabled is taking more time than usual.
Adding backend_cache: true (enabled) will improve performance. 
- https://github.com/inspec/kitchen-inspec/issues/212
=> enabling default backend cache

lib/kitchen/verifier/inspec.rb
Turns out that initializing the InSpec Config object causes it to examine the plugin list, so any unrecognized plugins will throw an exception.
Fixes #273
=> Load plugins prior to InSpec config validation

README.md, kitchen-inspec.gemspec, lib/kitchen/verifier/inspec.rb
- Upgrade Inspec version to major version 6
- Enable the ability to set chef_license_key using Kitchen
- Enable the ability to set chef_license_server using Kitchen
Via Kitchen **kitchen.yaml**
To configure verifier block with `chef_license_key` :
```
verifier:
name: inspec
chef_license_key: LICENSE_KEY
```
To configure verifier block with `chef_license_server` :
**Multiple URLS**
```
verifier:
name: inspec
chef_license_key: LICENSE_KEY
chef_license_server:
- https://test-url-1
- https://test-url-2
```
Or
**Single URL**
```
verifier:
name: inspec
chef_license_key: LICENSE_KEY
chef_license_server: https://test-url-1
```
=> CHEF-12879 Kitchen integration with InSpec 6 

kitchen-inspec.gemspec
Resolving a dependency conflict in hashie gem to ensure compatibility with chef-zero-15.0.11.
[List any existing issues this PR resolves, or any Discourse or
StackOverflow discussions that are relevant]
=> CHEF-20340 - Fix dependency conflict with hashie for chef-zero-15.0.11 
