CHANGELOG.md, lib/kitchen/verifier/inspec_version.rb
\cc @chris-rock @arlimus 
Minor version bump because of https://github.com/chef/kitchen-inspec/pull/27 and https://github.com/chef/kitchen-inspec/pull/24
=> Preparing the 0.10.0 release

Gemfile
bundler gets confused without this :(
=> Bump berks requirement to latest

lib/kitchen/verifier/inspec.rb
=> add output to runner options

kitchen-inspec.gemspec
in this release of kitchen-inspec
=> allow for slightly newer versions of inspec

README.md
This simply demonstrates that users can pass an array of profile sources under one test suite.
=> demonstrated utilizing an array of profile sources

.kitchen.yml, .travis.yml, README.md
=> update readme to reflect harmonization of profile location targets

.kitchen.yml
these have moved recently ...
Signed-off-by: Dominik Richter <dominik.richter@gmail.com>
=> update kitchen test references

lib/kitchen/verifier/inspec.rb
ping @aaronlippold in https://github.com/chef/inspec/issues/1738
=> add sudo_options support

CHANGELOG.md, lib/kitchen/verifier/inspec_version.rb
Bump version and changelog for release.
=> Release kitchen inspec 0.23.0

README.md
See the updated README rendered here: https://github.com/james-stocks/kitchen-inspec/tree/fix_readme
=> Fix inspec profile doc URL in README

CHANGELOG.md, lib/kitchen/verifier/inspec_version.rb
=> Release kitchen inspec 0.23.1

README.md, kitchen-inspec.gemspec
=> Update URLs for inspec not chef

lib/kitchen/verifier/inspec.rb
=> add support for private supermarkets

lib/kitchen/verifier/inspec.rb
As shown in #199 this would allow placeholders for reporters
=> Allow %{platform} and %{suite} placeholders for reporter option

README.md, lib/kitchen/verifier/inspec.rb
=> Fix platform and suite placeholders being applied incorrectly on reporter option

spec/kitchen/verifier/inspec_spec.rb
=> Add some testing around the reporter format replacements

README.md
follow-up fix for #190 
Signed-off-by: Christoph Hartmann <chris@lollyrock.com>
=> followup fix for #190

CHANGELOG.md, lib/kitchen/verifier/inspec_version.rb
=> Release 0.25

kitchen-inspec.gemspec
These are for testing only. Remove them from the gemspec and gem
artifact.
=> Don't ship the console and setup binaries

.expeditor/config.yml
Signed-off-by: Clinton Wolfe <clintoncwolfe@gmail.com>
The expeditor config is failing when trying to publish the rubygem, trying to call keys() on a String.  Let's give it a Hash.
=> Try to fix rubygems config

lib/kitchen/verifier/inspec.rb
#242 
- [N/A] New functionality includes tests
- [N/A] All tests pass
=> Add missing require causing lib to break when using inputs

lib/kitchen/verifier/inspec.rb
=> Correct minor spelling mistake

lib/kitchen/verifier/inspec.rb
Avoid creating objects we don't need.
=> Resolve RuboCop Style/RedundantAssignment

kitchen-inspec.gemspec
=> Fix hashi pin to be < 5

lib/kitchen/verifier/inspec.rb, spec/kitchen/verifier/inspec_spec.rb
Signed-off-by: Nikita Mathur <nikita.mathur@chef.io>
SSH agent forwarding option enabled for InSpec
Closes #249
=> SSH agent forwarding option enabled for InSpec

kitchen-inspec.gemspec
Nothing in the plugin needs to be updated for this new release.
=> Support Test Kitchen 3.0

README.md
- Remove explanation about attributes being deprecated as this process
has now finished
- Minor yaml linting fixes
- Show how to use external waiver files
None
=> Update README with Waivers usage

kitchen-inspec.gemspec
Permit InSpec versions < 6.0
[List any existing issues this PR resolves, or any Discourse or
StackOverflow discussions that are relevant]
=> CFINSPEC-61 Allow inspec 5

kitchen-inspec.gemspec
Signed-off-by: Clinton Wolfe <clintoncwolfe@gmail.com>
[Please describe what this change achieves]
[List any existing issues this PR resolves, or any Discourse or
StackOverflow discussions that are relevant]
=> Allow InSpec 6

Gemfile
[Please describe what this change achieves]
[List any existing issues this PR resolves, or any Discourse or
StackOverflow discussions that are relevant]
=> Update Gemfile to use chef-tk-enterprise from main branch.
